In [75]:
# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random


# Content-Based Filtering menggunakan Cosine Similarity

## Membuat rekomendasi berdasarkan kriteria
   rekomendasi berdasarkan kriteria menggunakan 4 kriteria<br>
    1.**Halal**<br>
    2.**Area merokok**<br>
    3.**Harga**<br>
    4.**Tempat Parkir**<br>

In [76]:
data ='Downloads/tempat_makan_2022-02-17.csv'
warung = pd.read_csv(data)
print(warung.info())
warung.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 747 entries, 0 to 746
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   ID              747 non-null    int64  
 1   Latitude        747 non-null    float64
 2   Longitude       747 non-null    float64
 3   Nama_warung     747 non-null    object 
 4   Alamat          747 non-null    object 
 5   Halal           747 non-null    object 
 6   Area_merokok    747 non-null    object 
 7   Harga           747 non-null    object 
 8   Tempat_parkir   747 non-null    object 
 9   Masakan         746 non-null    object 
 10  Makanan         747 non-null    object 
 11  Jenis_warung    747 non-null    object 
 12  Makan_ditempat  747 non-null    object 
 13  Rating          747 non-null    float64
 14  Review          747 non-null    int64  
 15  Gambar          747 non-null    object 
dtypes: float64(3), int64(2), object(11)
memory usage: 61.3+ KB
None


ID  Latitude   Longitude                          Nama_warung  \
0   1 -7.768875  110.317707                 Warung Bakso Babi 08   
1   2 -7.765697  110.344304           Rumah Makan 88 / panpan 88   
2   3 -7.755880  110.383782  Kafe Djawa a.k.a Angkringan Enaknan   
3   4 -7.784784  110.370503                 Kali Code Angkringan   
4   5 -7.755350  110.376957                     Angkringan Kebun   

                                              Alamat      Halal Area_merokok  \
0  Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...  non-halal          Ada   
1  Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...  non-halal          Ada   
2  Jalan Kaliurang Km.5,8, Gang Pandega Satya No....      halal          Ada   
3  Jl. Prau, Kotabaru, Kec. Gondokusuman, Kota Yo...      halal          Ada   
4  Jl. Pandega Marta Jl. Pogung Lor No.316, RT.03...      halal          Ada   

   Harga       Tempat_parkir                    Masakan  \
0  Murah  off-street-parking                  Indonesia   
1  Mahal   on-street-parking   Chinese,Indonesia,Fusion   
2  Murah   on-street-parking        Jawa,Indonesia,Kafe   
3  Murah   on-street-parking  Jawa,Indonesia,Yogyakarta   
4  Murah   on-street-parking  Jawa,Indonesia,Yogyakarta   

                                       Makanan  \
0                              Sate,Pork,Bakso   
1                                         Pork   
2                 Ayam,Daging,Mie,Kopi,Minuman   
3                                Sate,Gorengan   
4  Sate,Nasi Goreng,Pecel,Mie,Minuman,Gorengan   

                         Jenis_warung    Makan_ditempat  Rating  Review  \
0                         Quick Bites  Dine-in/Takeaway     4.5      52   
1                         Quick Bites  Dine-in/Takeaway     4.6     671   
2     Kafe,Restoran kasual,Angkringan  Dine-in/Takeaway     4.6     531   
3  Quick Bites,Street Food,Angkringan  Dine-in/Takeaway     4.3     969   
4              Quick Bites,Angkringan  Dine-in/Takeaway     4.9     143   

                                              Gambar  
0  https://lh5.googleusercontent.com/p/AF1QipNaby...  
1  https://lh5.googleusercontent.com/p/AF1QipMuA7...  
2  https://lh5.googleusercontent.com/p/AF1QipNmmT...  
3  https://lh5.googleusercontent.com/p/AF1QipMMru...  
4  https://lh5.googleusercontent.com/p/AF1QipOu__...

In [77]:
warung['Halal'] = warung['Halal'].str.lower()
warung['Harga'] = warung['Harga'].str.lower()
warung['Area_merokok']= warung['Area_merokok'].str.lower()
warung['Tempat_parkir'] = warung['Tempat_parkir'].str.lower()

In [78]:
warung

ID  Latitude   Longitude                          Nama_warung  \
0      1 -7.768875  110.317707                 Warung Bakso Babi 08   
1      2 -7.765697  110.344304           Rumah Makan 88 / panpan 88   
2      3 -7.755880  110.383782  Kafe Djawa a.k.a Angkringan Enaknan   
3      4 -7.784784  110.370503                 Kali Code Angkringan   
4      5 -7.755350  110.376957                     Angkringan Kebun   
..   ...       ...         ...                                  ...   
742  745 -7.777875  110.345271                  Shiki Japanese Food   
743  746 -7.765771  110.405852         WAROENK RAMEN PERUMNAS JOGJA   
744  747 -7.881513  110.341594              Rock N Roll Sushi Ramen   
745  748 -7.778105  110.392818          Hakata Ikkousha Ramen Resto   
746  749 -7.772985  110.404782       HanBingo Korean Food & Dessert   

                                                Alamat      Halal  \
0    Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...  non-halal   
1    Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...  non-halal   
2    Jalan Kaliurang Km.5,8, Gang Pandega Satya No....      halal   
3    Jl. Prau, Kotabaru, Kec. Gondokusuman, Kota Yo...      halal   
4    Jl. Pandega Marta Jl. Pogung Lor No.316, RT.03...      halal   
..                                                 ...        ...   
742  Jl. Nusa Indah No.127, Kwarasan, Nogotirto, Ke...      halal   
743  Jl. Perumnas No.29, Dabag, Condongcatur, Kec. ...      halal   
744  Jl. Pramuka, Area Sawah, Trirenggo, Kec. Bantu...      halal   
745  Ruko Demangan, Kav 2-3, Jl. Demangan Baru No.1...      halal   
746  Jl. Perumnas No.93, Dabag, Condongcatur, Kec. ...      halal   

    Area_merokok  Harga       Tempat_parkir                    Masakan  \
0            ada  murah  off-street-parking                  Indonesia   
1            ada  mahal   on-street-parking   Chinese,Indonesia,Fusion   
2            ada  murah   on-street-parking        Jawa,Indonesia,Kafe   
3            ada  murah   on-street-parking  Jawa,Indonesia,Yogyakarta   
4            ada  murah   on-street-parking  Jawa,Indonesia,Yogyakarta   
..           ...    ...                 ...                        ...   
742        tidak  murah   on-street-parking                Jepang,Asia   
743          ada  murah  off-street-parking                Jepang,Asia   
744          ada  murah   on-street-parking                Jepang,Asia   
745        tidak  mahal  off-street-parking                Jepang,Asia   
746        tidak  mahal  off-street-parking                 Korea,Asia   

                                         Makanan  \
0                                Sate,Pork,Bakso   
1                                           Pork   
2                   Ayam,Daging,Mie,Kopi,Minuman   
3                                  Sate,Gorengan   
4    Sate,Nasi Goreng,Pecel,Mie,Minuman,Gorengan   
..                                           ...   
742                                   Ayam,Sushi   
743                               Ayam,Mie,Sushi   
744                                    Mie,Sushi   
745                        Ayam,Daging,Mie,Sushi   
746                                  Ayam,Daging   

                           Jenis_warung    Makan_ditempat  Rating  Review  \
0                           Quick Bites  Dine-in/Takeaway     4.5      52   
1                           Quick Bites  Dine-in/Takeaway     4.6     671   
2       Kafe,Restoran kasual,Angkringan  Dine-in/Takeaway     4.6     531   
3    Quick Bites,Street Food,Angkringan  Dine-in/Takeaway     4.3     969   
4                Quick Bites,Angkringan  Dine-in/Takeaway     4.9     143   
..                                  ...               ...     ...     ...   
742         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.8     114   
743         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.2     675   
744         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.4     390   
745   Restoran kasual,Restoran Keluarga 

In [79]:
warung['Halal'] = warung['Halal'].replace('non-halal','non halal')
warung['Tempat_parkir'] = warung['Tempat_parkir'].replace('off-street-parking','off street parking')
warung['Tempat_parkir'] = warung['Tempat_parkir'].replace('on-street-parking','on street parking')

In [80]:
warung['kriteria'] = warung['Halal'].str.cat(
    warung[['Area_merokok','Harga','Tempat_parkir','Halal']],
    sep=' '
)

In [81]:
import re
warung['kriteria'] = warung['kriteria'].apply(lambda x: ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", x).split()))


In [82]:
warung.iloc[230]

ID                                                              233
Latitude                                                   -7.74777
Longitude                                                   110.362
Nama_warung                        Babi Q Resto Khusus Masakan Babi
Alamat            Unnamed Road, 55284, Mlati Dukuh, Sendangadi, ...
Halal                                                     non halal
Area_merokok                                                  tidak
Harga                                                      menengah
Tempat_parkir                                     on street parking
Masakan                              Chinese,Medan,Indonesia,Fusion
Makanan                                                   Sate,Pork
Jenis_warung                            Restoran kasual,Quick Bites
Makan_ditempat                                     Dine-in/Takeaway
Rating                                                          4.5
Review                                          

In [83]:
warung.to_csv('warung.csv', index = False)

In [84]:
test1 =pd.read_csv('warung.csv')
test1

ID  Latitude   Longitude                          Nama_warung  \
0      1 -7.768875  110.317707                 Warung Bakso Babi 08   
1      2 -7.765697  110.344304           Rumah Makan 88 / panpan 88   
2      3 -7.755880  110.383782  Kafe Djawa a.k.a Angkringan Enaknan   
3      4 -7.784784  110.370503                 Kali Code Angkringan   
4      5 -7.755350  110.376956                     Angkringan Kebun   
..   ...       ...         ...                                  ...   
742  745 -7.777875  110.345272                  Shiki Japanese Food   
743  746 -7.765771  110.405852         WAROENK RAMEN PERUMNAS JOGJA   
744  747 -7.881513  110.341594              Rock N Roll Sushi Ramen   
745  748 -7.778105  110.392818          Hakata Ikkousha Ramen Resto   
746  749 -7.772985  110.404782       HanBingo Korean Food & Dessert   

                                                Alamat      Halal  \
0    Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...  non halal   
1    Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...  non halal   
2    Jalan Kaliurang Km.5,8, Gang Pandega Satya No....      halal   
3    Jl. Prau, Kotabaru, Kec. Gondokusuman, Kota Yo...      halal   
4    Jl. Pandega Marta Jl. Pogung Lor No.316, RT.03...      halal   
..                                                 ...        ...   
742  Jl. Nusa Indah No.127, Kwarasan, Nogotirto, Ke...      halal   
743  Jl. Perumnas No.29, Dabag, Condongcatur, Kec. ...      halal   
744  Jl. Pramuka, Area Sawah, Trirenggo, Kec. Bantu...      halal   
745  Ruko Demangan, Kav 2-3, Jl. Demangan Baru No.1...      halal   
746  Jl. Perumnas No.93, Dabag, Condongcatur, Kec. ...      halal   

    Area_merokok  Harga       Tempat_parkir                    Masakan  \
0            ada  murah  off street parking                  Indonesia   
1            ada  mahal   on street parking   Chinese,Indonesia,Fusion   
2            ada  murah   on street parking        Jawa,Indonesia,Kafe   
3            ada  murah   on street parking  Jawa,Indonesia,Yogyakarta   
4            ada  murah   on street parking  Jawa,Indonesia,Yogyakarta   
..           ...    ...                 ...                        ...   
742        tidak  murah   on street parking                Jepang,Asia   
743          ada  murah  off street parking                Jepang,Asia   
744          ada  murah   on street parking                Jepang,Asia   
745        tidak  mahal  off street parking                Jepang,Asia   
746        tidak  mahal  off street parking                 Korea,Asia   

                                         Makanan  \
0                                Sate,Pork,Bakso   
1                                           Pork   
2                   Ayam,Daging,Mie,Kopi,Minuman   
3                                  Sate,Gorengan   
4    Sate,Nasi Goreng,Pecel,Mie,Minuman,Gorengan   
..                                           ...   
742                                   Ayam,Sushi   
743                               Ayam,Mie,Sushi   
744                                    Mie,Sushi   
745                        Ayam,Daging,Mie,Sushi   
746                                  Ayam,Daging   

                           Jenis_warung    Makan_ditempat  Rating  Review  \
0                           Quick Bites  Dine-in/Takeaway     4.5      52   
1                           Quick Bites  Dine-in/Takeaway     4.6     671   
2       Kafe,Restoran kasual,Angkringan  Dine-in/Takeaway     4.6     531   
3    Quick Bites,Street Food,Angkringan  Dine-in/Takeaway     4.3     969   
4                Quick Bites,Angkringan  Dine-in/Takeaway     4.9     143   
..                                  ...               ...     ...     ...   
742         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.8     114   
743         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.2     675   
744         Restoran kasual,Quick Bites  Dine-in/Takeaway     4.4     390   
745   Restoran kasual,Restoran Keluarga 

In [85]:
#count kriteria
model = CountVectorizer(
    tokenizer = lambda i: i.split(' '), # -> cari split karakter yang unik
    analyzer = 'word'
)
matrix_kriteria = model.fit_transform(warung['kriteria'])
tipe_kriteria = model.get_feature_names()
jumlah_kriteria = len(tipe_kriteria)
event_kriteria = matrix_kriteria.toarray()

In [86]:
print (tipe_kriteria)

['ada', 'halal', 'mahal', 'menengah', 'murah', 'non', 'off', 'on', 'parking', 'street', 'tidak']


In [87]:
print (jumlah_kriteria)

11


In [88]:
print(event_kriteria)

[[1 2 0 ... 1 1 0]
 [1 2 1 ... 1 1 0]
 [1 2 0 ... 1 1 0]
 ...
 [1 2 0 ... 1 1 0]
 [0 2 1 ... 1 1 1]
 [0 2 1 ... 1 1 1]]


In [89]:
print(event_kriteria[230])
print(event_kriteria[234])

[0 2 0 1 0 2 0 1 1 1 1]
[1 2 0 1 0 2 0 1 1 1 0]


In [90]:
print(event_kriteria[1])
print(event_kriteria[2])

[1 2 1 0 0 2 0 1 1 1 0]
[1 2 0 0 1 0 0 1 1 1 0]


In [91]:
print(matrix_kriteria[230])

  (0, 5)	2
  (0, 1)	2
  (0, 9)	1
  (0, 8)	1
  (0, 7)	1
  (0, 10)	1
  (0, 3)	1


In [92]:
score = cosine_similarity(matrix_kriteria)
score

array([[1.        , 0.84615385, 0.73960026, ..., 0.73960026, 0.64715023,
        0.64715023],
       [0.84615385, 1.        , 0.73960026, ..., 0.73960026, 0.64715023,
        0.64715023],
       [0.73960026, 0.73960026, 1.        , ..., 1.        , 0.66666667,
        0.66666667],
       ...,
       [0.73960026, 0.73960026, 1.        , ..., 1.        , 0.66666667,
        0.66666667],
       [0.64715023, 0.64715023, 0.66666667, ..., 0.66666667, 1.        ,
        1.        ],
       [0.64715023, 0.64715023, 0.66666667, ..., 0.66666667, 1.        ,
        1.        ]])

## Membuat Cosine Similarity Score

In [93]:
#cosine similarity
score = cosine_similarity(matrix_kriteria)
score

array([[1.        , 0.84615385, 0.73960026, ..., 0.73960026, 0.64715023,
        0.64715023],
       [0.84615385, 1.        , 0.73960026, ..., 0.73960026, 0.64715023,
        0.64715023],
       [0.73960026, 0.73960026, 1.        , ..., 1.        , 0.66666667,
        0.66666667],
       ...,
       [0.73960026, 0.73960026, 1.        , ..., 1.        , 0.66666667,
        0.66666667],
       [0.64715023, 0.64715023, 0.66666667, ..., 0.66666667, 1.        ,
        1.        ],
       [0.64715023, 0.64715023, 0.66666667, ..., 0.66666667, 1.        ,
        1.        ]])

## Membuat Machine Learning Prdiction
membuat dummy dataframe untuk prosses kategori data yand ada didalam kolom kriteria

In [94]:
warung_dummy = pd.get_dummies(
    warung,
    columns = ['Halal','Area_merokok','Harga','Tempat_parkir'], 
)
display(warung_dummy.head())

ID  Latitude   Longitude                          Nama_warung  \
0   1 -7.768875  110.317707                 Warung Bakso Babi 08   
1   2 -7.765697  110.344304           Rumah Makan 88 / panpan 88   
2   3 -7.755880  110.383782  Kafe Djawa a.k.a Angkringan Enaknan   
3   4 -7.784784  110.370503                 Kali Code Angkringan   
4   5 -7.755350  110.376957                     Angkringan Kebun   

                                              Alamat  \
0  Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...   
1  Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...   
2  Jalan Kaliurang Km.5,8, Gang Pandega Satya No....   
3  Jl. Prau, Kotabaru, Kec. Gondokusuman, Kota Yo...   
4  Jl. Pandega Marta Jl. Pogung Lor No.316, RT.03...   

                     Masakan                                      Makanan  \
0                  Indonesia                              Sate,Pork,Bakso   
1   Chinese,Indonesia,Fusion                                         Pork   
2        Jawa,Indonesia,Kafe                 Ayam,Daging,Mie,Kopi,Minuman   
3  Jawa,Indonesia,Yogyakarta                                Sate,Gorengan   
4  Jawa,Indonesia,Yogyakarta  Sate,Nasi Goreng,Pecel,Mie,Minuman,Gorengan   

                         Jenis_warung    Makan_ditempat  Rating  ...  \
0                         Quick Bites  Dine-in/Takeaway     4.5  ...   
1                         Quick Bites  Dine-in/Takeaway     4.6  ...   
2     Kafe,Restoran kasual,Angkringan  Dine-in/Takeaway     4.6  ...   
3  Quick Bites,Street Food,Angkringan  Dine-in/Takeaway     4.3  ...   
4              Quick Bites,Angkringan  Dine-in/Takeaway     4.9  ...   

                                           kriteria Halal_halal  \
0  non halal ada murah off street parking non halal           0   
1   non halal ada mahal on street parking non halal           0   
2           halal ada murah on street parking halal           1   
3           halal ada murah on street parking halal           1   
4           halal ada murah on street parking halal           1   

  Halal_non halal  Area_merokok_ada  Area_merokok_tidak  Harga_mahal  \
0               1                 1                   0            0   
1               1                 1                   0            1   
2               0                 1                   0            0   
3               0                 1                   0            0   
4               0                 1                   0            0   

   Harga_menengah  Harga_murah  Tempat_parkir_off street parking  \
0               0            1                                 1   
1               0            0                                 0   
2               0            1                                 0   
3               0            1                                 0   
4               0            1                                 0   

   Tempat_parkir_on street parking  
0                                0  
1                                1  
2                                1  
3                                1  
4                                1  

[5 rows x 22 columns]

menentukan variabel independen dan dependent

In [154]:
#label encoder
from sklearn.preprocessing import LabelEncoder
category_col = ['Halal','Area_merokok','Harga','Tempat_parkir']
labelencoder = LabelEncoder()
warung['kriteria_cat'] = labelencoder.fit_transform(warung['kriteria'])
warung.head()


ID  Latitude   Longitude                          Nama_warung  \
0   1 -7.768875  110.317707                 Warung Bakso Babi 08   
1   2 -7.765697  110.344304           Rumah Makan 88 / panpan 88   
2   3 -7.755880  110.383782  Kafe Djawa a.k.a Angkringan Enaknan   
3   4 -7.784784  110.370503                 Kali Code Angkringan   
4   5 -7.755350  110.376957                     Angkringan Kebun   

                                              Alamat      Halal Area_merokok  \
0  Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...  non halal          ada   
1  Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...  non halal          ada   
2  Jalan Kaliurang Km.5,8, Gang Pandega Satya No....      halal          ada   
3  Jl. Prau, Kotabaru, Kec. Gondokusuman, Kota Yo...      halal          ada   
4  Jl. Pandega Marta Jl. Pogung Lor No.316, RT.03...      halal          ada   

   Harga       Tempat_parkir                    Masakan  \
0  murah  off street parking                  Indonesia   
1  mahal   on street parking   Chinese,Indonesia,Fusion   
2  murah   on street parking        Jawa,Indonesia,Kafe   
3  murah   on street parking  Jawa,Indonesia,Yogyakarta   
4  murah   on street parking  Jawa,Indonesia,Yogyakarta   

                                       Makanan  \
0                              Sate,Pork,Bakso   
1                                         Pork   
2                 Ayam,Daging,Mie,Kopi,Minuman   
3                                Sate,Gorengan   
4  Sate,Nasi Goreng,Pecel,Mie,Minuman,Gorengan   

                         Jenis_warung    Makan_ditempat  Rating  Review  \
0                         Quick Bites  Dine-in/Takeaway     4.5      52   
1                         Quick Bites  Dine-in/Takeaway     4.6     671   
2     Kafe,Restoran kasual,Angkringan  Dine-in/Takeaway     4.6     531   
3  Quick Bites,Street Food,Angkringan  Dine-in/Takeaway     4.3     969   
4              Quick Bites,Angkringan  Dine-in/Takeaway     4.9     143   

                                              Gambar  \
0  https://lh5.googleusercontent.com/p/AF1QipNaby...   
1  https://lh5.googleusercontent.com/p/AF1QipMuA7...   
2  https://lh5.googleusercontent.com/p/AF1QipNmmT...   
3  https://lh5.googleusercontent.com/p/AF1QipMMru...   
4  https://lh5.googleusercontent.com/p/AF1QipOu__...   

                                           kriteria  kriteria_cat  
0  non halal ada murah off street parking non halal            16  
1   non halal ada mahal on street parking non halal            13  
2           halal ada murah on street parking halal             5  
3           halal ada murah on street parking halal             5  
4           halal ada murah on street parking halal             5

In [155]:
x = warung_dummy.drop(
    ['ID','Latitude','Longitude','Nama_warung','Alamat','Masakan','Makanan',
    'Makan_ditempat','kriteria','Jenis_warung','Rating','Review','Gambar'], axis=1
)
display(x.head())

Halal_halal  Halal_non halal  Area_merokok_ada  Area_merokok_tidak  \
0            0                1                 1                   0   
1            0                1                 1                   0   
2            1                0                 1                   0   
3            1                0                 1                   0   
4            1                0                 1                   0   

   Harga_mahal  Harga_menengah  Harga_murah  Tempat_parkir_off street parking  \
0            0               0            1                                 1   
1            1               0            0                                 0   
2            0               0            1                                 0   
3            0               0            1                                 0   
4            0               0            1                                 0   

   Tempat_parkir_on street parking  
0                                0  
1                                1  
2                                1  
3                                1  
4                                1

In [156]:
display(x)

Halal_halal  Halal_non halal  Area_merokok_ada  Area_merokok_tidak  \
0              0                1                 1                   0   
1              0                1                 1                   0   
2              1                0                 1                   0   
3              1                0                 1                   0   
4              1                0                 1                   0   
..           ...              ...               ...                 ...   
742            1                0                 0                   1   
743            1                0                 1                   0   
744            1                0                 1                   0   
745            1                0                 0                   1   
746            1                0                 0                   1   

     Harga_mahal  Harga_menengah  Harga_murah  \
0              0               0            1   
1              1               0            0   
2              0               0            1   
3              0               0            1   
4              0               0            1   
..           ...             ...          ...   
742            0               0            1   
743            0               0            1   
744            0               0            1   
745            1               0            0   
746            1               0            0   

     Tempat_parkir_off street parking  Tempat_parkir_on street parking  
0                                   1                                0  
1                                   0                                1  
2                                   0                                1  
3                                   0                                1  
4                                   0                                1  
..                                ...                              ...  
742                                 0                                1  
743                                 1                                0  
744                                 0                                1  
745                                 1                                0  
746                                 1                                0  

[747 rows x 9 columns]

In [157]:
y = warung_dummy['Nama_warung']
display(y.head())

0                   Warung Bakso Babi 08
1             Rumah Makan 88 / panpan 88
2    Kafe Djawa a.k.a Angkringan Enaknan
3                   Kali Code Angkringan
4                       Angkringan Kebun
Name: Nama_warung, dtype: object

In [158]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x, y, test_size = 0.67, random_state = 5)

In [68]:
print(X_train.shape)
X_train

(246, 9)


Halal_halal  Halal_non halal  Area_merokok_ada  Area_merokok_tidak  \
570            1                0                 1                   0   
213            1                0                 1                   0   
583            1                0                 1                   0   
83             1                0                 0                   1   
92             1                0                 1                   0   
..           ...              ...               ...                 ...   
73             1                0                 1                   0   
400            1                0                 1                   0   
118            1                0                 0                   1   
701            1                0                 1                   0   
206            1                0                 1                   0   

     Harga_mahal  Harga_menengah  Harga_murah  \
570            0               0            1   
213            0               0            1   
583            0               1            0   
83             0               1            0   
92             0               0            1   
..           ...             ...          ...   
73             0               1            0   
400            0               0            1   
118            0               1            0   
701            0               1            0   
206            0               0            1   

     Tempat_parkir_off street parking  Tempat_parkir_on street parking  
570                                 0                                1  
213                                 0                                1  
583                                 1                                0  
83                                  1                                0  
92                                  0                                1  
..                                ...                              ...  
73                                  1                                0  
400                                 0                                1  
118                                 0                                1  
701                                 1                                0  
206                                 0                                1  

[246 rows x 9 columns]

In [69]:
print(X_test.shape)

(501, 9)


In [70]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [160]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state =1234)
rf_clf.fit(X_train, y_train)

# scoring model
print('Accuracy = {}%'.format(round(rf_clf.score(X_train, y_train) * 100, 2)))
# print(rf_clf.score(x, y))
# prediction
# print(rf_clf.predict([[1,0,1,0,0,0,1,1,0]])[0])

y_pred = rf_clf.predict(X_test)

Accuracy = 7.32%


<i>Machine Learning</i> memprediksi nama warung berdasarkan kriteria berikut :<br>
<br>
 1.**Halal** = **halal**<br>
 2.**Area Merokok** = **Ada**<br>
 3.**Harga** = **Murah**<br>
 4.**Tempat Parkir** = **off-street-parking**<br>

In [172]:
# logistic regression model
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver = 'liblinear', multi_class = 'auto')
log_reg.fit(x, y)

# scoring model
print('Accuracy = {}%'.format(round(log_reg.score(x, y) * 100, 2)))

# prediction
print(log_reg.predict([[1,0,1,0,0,0,1,1,0]])[0])

Accuracy = 2.81%
Mugi Mojo Kitchen


In [80]:
# kernel svm model
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf', gamma = 0.5)
svm.fit(x, y)

# scoring model
print('Accuracy = {}%'.format(round(svm.score(x, y) * 100, 2)))

# prediction
print(svm.predict([[1,0,1,0,0,0,1,1,0]])[0])

Accuracy = 2.81%
kitchen Oriental Seafood


In [103]:
# naive bayes model
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# scoring model
print('Accuracy = {}%'.format(round(gnb.score(x, y) * 100, 2)))

# prediction
print(gnb.predict([[1,0,1,0,0,0,1,1,0]])[0])

Accuracy = 2.41%
Aneka Bubur "Assalam"


In [102]:
# decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dct_clf = DecisionTreeClassifier(criterion = 'entropy')
dct_clf.fit(X_train, y_train)

# scoring model
print('Accuracy = {}%'.format(round(dct_clf.score(x, y) * 100, 2)))

# prediction
print(dct_clf.predict([[0,1,1,0,0,0,1,1,0]])[0])

Accuracy = 2.41%
Aneka Bubur "Assalam"


In [159]:
# random forest model
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state =0)
rf_clf.fit(X_test, y_test)

# prediction
print(rf_clf.predict([[0,1,1,0,1,0,0,1,0]])[0])

# scoring model
print('Accuracy = {}%'.format(round(rf_clf.score(x, y) * 100, 2)))

Kong Kong Chinese & Seafood
Accuracy = 2.41%


In [84]:
display(warung[warung['Nama_warung'] == 'Mugi Mojo Kitchen'])
display(warung[warung['Nama_warung'] == 'kitchen Oriental Seafood'])
display(warung[warung['Nama_warung'] == 'Aneka Bubur "Assalam"'])
display(warung[warung['Nama_warung'] == 'Woko Wader mangut'])

ID  Latitude   Longitude        Nama_warung  \
258  261 -7.724268  110.380645  Mugi Mojo Kitchen   

                                                Alamat  Halal Area_merokok  \
258  Jl. Sadewa No.414, Tegal Rejo, Sariharjo, Kec....  halal          ada   

     Harga       Tempat_parkir         Masakan           Makanan  \
258  murah  off street parking  Jawa,Indonesia  Tahu Tek,Lontong   

                    Jenis_warung    Makan_ditempat  Rating  Review  \
258  Restoran kasual,Quick Bites  Dine-in/Takeaway     5.0       6   

                                                Gambar  \
258  https://lh5.googleusercontent.com/p/AF1QipPWEX...   

                               kriteria  
258  halal ada murah off street parking

ID  Latitude   Longitude               Nama_warung  \
690  693 -7.750924  110.410149  kitchen Oriental Seafood   

                                                Alamat  Halal Area_merokok  \
690  Jl. Super Raya No.169-177, Dero, Condongcatur,...  halal          ada   

     Harga       Tempat_parkir                        Masakan  \
690  murah  off street parking  Chinese,Indonesia,Asia,Fusion   

                         Makanan                 Jenis_warung  \
690  Ayam,Ikan,Seafood,Hot Plate  Restoran kasual,Quick Bites   

       Makan_ditempat  Rating  Review  \
690  Dine-in/Takeaway     4.7     136   

                                                Gambar  \
690  https://lh5.googleusercontent.com/p/AF1QipOWt7...   

                               kriteria  
690  halal ada murah off street parking

ID  Latitude   Longitude            Nama_warung  \
622  625 -7.760825  110.380502  Aneka Bubur "Assalam"   

                                                Alamat  Halal Area_merokok  \
622  Karang Wuni, Caturtunggal, Kec. Depok, Kabupat...  halal          ada   

     Harga       Tempat_parkir    Masakan           Makanan Jenis_warung  \
622  murah  off street parking  Indonesia  Bubur Kacang Ijo  Quick Bites   

       Makan_ditempat  Rating  Review  \
622  Dine-in/Takeaway     4.1      25   

                                                Gambar  \
622  https://lh5.googleusercontent.com/p/AF1QipOq3x...   

                               kriteria  
622  halal ada murah off street parking

ID  Latitude   Longitude        Nama_warung  \
590  593 -7.831751  110.463049  Woko Wader mangut   

                                          Alamat  Halal Area_merokok  Harga  \
590  Onggoparum, Srimulyo, Kec. Piyungan, Bantul  halal          ada  murah   

          Tempat_parkir                    Masakan           Makanan  \
590  off street parking  Jawa,Indonesia,Yogyakarta  Ikan,Mangut Lele   

                    Jenis_warung    Makan_ditempat  Rating  Review  \
590  Restoran kasual,Quick Bites  Dine-in/Takeaway     4.5     133   

                                                Gambar  \
590  https://lh5.googleusercontent.com/p/AF1QipPWXX...   

                               kriteria  
590  halal ada murah off street parking

<h2> Membuat <i>recommendation System</i> berdasarkan kriteria</h2> <br>
    dari hasil prediksi yang didapat penelti memilih <i>Random Forest Classifer</i> peneliti ingin mendapatkan 5 rekoemdasi yang meiliki <i>cosine similarity</i> > 84%

In [173]:
# test model 1, 0, 0, 1, 0, 0, 1, 0, 1
warung_fav = rf_clf.predict([[0,1,1,0,0,0,1,1,0]])[0]

display(warung[warung['Nama_warung'] == warung_fav])

# take the index from warung_fav
index_fav = warung[warung['Nama_warung'] == warung_fav].index.values[0]
# print(index_fav)

# list all restuarants + cosine similarity score
all_warung = list(enumerate(score[index_fav]))
# print(all_warung)

# show similar restaurant, sorted by score
warung_similar = sorted(
    all_warung,
    key = lambda i: i[1],
    reverse = True
)
# print(resto_similar)

ID  Latitude   Longitude     Nama_warung  \
233  236 -7.773472  110.411075  Depot babi YOE   

                                                Alamat      Halal  \
233  Unnamed Road, Kledokan, Caturtunggal, Kec. Dep...  non halal   

    Area_merokok  Harga      Tempat_parkir         Masakan  \
233          ada  murah  on street parking  Jawa,Indonesia   

                       Makanan Jenis_warung    Makan_ditempat  Rating  Review  \
233  Sate,Pork,Nasi Goreng,Mie  Quick Bites  Dine-in/Takeaway     4.7       6   

                                                Gambar  \
233  https://lh5.googleusercontent.com/p/AF1QipOx3r...   

                                            kriteria  kriteria_cat  
233  non halal ada murah on street parking non halal            17

In [186]:
warung.iloc[248]

ID                                                              251
Latitude                                                   -7.78632
Longitude                                                   110.302
Nama_warung                DJOMED br. Tampubolon ( Rm daging babi )
Alamat            Jalan Pandawa RT.05/RW.18, Gancakan Wetan, Sid...
Halal                                                     non halal
Area_merokok                                                    ada
Harga                                                      menengah
Tempat_parkir                                    off street parking
Masakan                              Chinese,Medan,Indonesia,Fusion
Makanan                            Pork,Nasi Goreng,Soto,Sop,Bakmie
Jenis_warung                            Restoran kasual,Quick Bites
Makan_ditempat                                     Dine-in/Takeaway
Rating                                                          4.7
Review                                          

In [175]:
all_warung

[(0, 0.9230769230769231),
 (1, 0.9230769230769229),
 (2, 0.8320502943378435),
 (3, 0.8320502943378435),
 (4, 0.8320502943378435),
 (5, 0.8320502943378435),
 (6, 0.8320502943378435),
 (7, 0.554700196225229),
 (8, 0.554700196225229),
 (9, 0.554700196225229),
 (10, 0.554700196225229),
 (11, 0.554700196225229),
 (12, 0.554700196225229),
 (13, 0.6471502289294339),
 (14, 0.7396002616336387),
 (15, 0.6471502289294339),
 (16, 0.7396002616336387),
 (17, 0.6471502289294339),
 (18, 0.7396002616336387),
 (19, 0.846153846153846),
 (20, 0.6471502289294339),
 (21, 0.6471502289294339),
 (22, 0.554700196225229),
 (23, 0.554700196225229),
 (24, 0.6471502289294339),
 (25, 0.7396002616336387),
 (26, 0.6471502289294339),
 (27, 0.8320502943378435),
 (28, 0.8320502943378435),
 (29, 0.8320502943378435),
 (30, 0.8320502943378435),
 (31, 0.8320502943378435),
 (32, 0.8320502943378435),
 (33, 0.6471502289294339),
 (34, 0.7396002616336387),
 (35, 0.7396002616336387),
 (36, 0.7396002616336387),
 (37, 0.647150228929

In [176]:
warung_similar

[(233, 1.0),
 (242, 1.0),
 (244, 1.0),
 (245, 1.0),
 (246, 1.0),
 (0, 0.9230769230769231),
 (1, 0.9230769230769229),
 (232, 0.9230769230769229),
 (234, 0.9230769230769229),
 (237, 0.9230769230769229),
 (240, 0.9230769230769229),
 (241, 0.9230769230769229),
 (243, 0.9230769230769229),
 (247, 0.9230769230769229),
 (305, 0.9230769230769229),
 (341, 0.9230769230769229),
 (19, 0.846153846153846),
 (230, 0.846153846153846),
 (235, 0.846153846153846),
 (236, 0.846153846153846),
 (238, 0.846153846153846),
 (239, 0.846153846153846),
 (248, 0.846153846153846),
 (2, 0.8320502943378435),
 (3, 0.8320502943378435),
 (4, 0.8320502943378435),
 (5, 0.8320502943378435),
 (6, 0.8320502943378435),
 (27, 0.8320502943378435),
 (28, 0.8320502943378435),
 (29, 0.8320502943378435),
 (30, 0.8320502943378435),
 (31, 0.8320502943378435),
 (32, 0.8320502943378435),
 (67, 0.8320502943378435),
 (68, 0.8320502943378435),
 (69, 0.8320502943378435),
 (86, 0.8320502943378435),
 (88, 0.8320502943378435),
 (90, 0.83205029

In [247]:
# list all warung filter by cosine similarity score > 75%
warung_recom = []
for i in warung_similar:
    if i[1] >= 0.84:
        warung_recom.append(i)
    else:
        pass

# show 5 datas randomly
import random
#random.sample(range(23), 10)
for i in range(23):
    rekomendasi = random.sample(warung_recom, 10)
#rekomendasi = random.choices(list(warung_recom), k = 10)

for i in rekomendasi:
    print('Warung = {} | Halal = {} | Area Merokok = {} | Harga = {} | Tempat parkir = {}'.format(
        warung.iloc[i[0]]['Nama_warung'],
        warung.iloc[i[0]]['Halal'],
        warung.iloc[i[0]]['Area_merokok'],
        warung.iloc[i[0]]['Harga'],
        warung.iloc[i[0]]['Tempat_parkir'])
    )

    

Warung = Warung Makan Bu Kadek Khas Bali | Halal = non halal | Area Merokok = ada | Harga = menengah | Tempat parkir = off street parking
Warung = Warung Bakso Babi 08 | Halal = non halal | Area Merokok = ada | Harga = murah | Tempat parkir = off street parking
Warung = Babi Q Resto Khusus Masakan Babi | Halal = non halal | Area Merokok = tidak | Harga = menengah | Tempat parkir = on street parking
Warung = Bak & Mie - Spesial Babi Geprek & Mie Babi | Halal = non halal | Area Merokok = ada | Harga = menengah | Tempat parkir = on street parking
Warung = Kedai Piggies | Halal = non halal | Area Merokok = ada | Harga = menengah | Tempat parkir = on street parking
Warung = Babi Panggang Racing Koh JW | Halal = non halal | Area Merokok = tidak | Harga = mahal | Tempat parkir = on street parking
Warung = Warung Babi Si Lae | Halal = non halal | Area Merokok = ada | Harga = murah | Tempat parkir = on street parking
Warung = bakso dan sate Babi pak Har | Halal = non halal | Area Merokok = ada 

In [236]:
all_lines = f1.readlines()

NameError: name 'f1' is not defined

In [198]:
#rekomendasi = random.choices(warung_recom, k = 5)
list_rekom = []
for i in warung_recom[:5]:
    ambil_rekom = {}
    ambil_rekom['Nama_warung'] = warung.iloc[i[0]]['Nama_warung'],
    ambil_rekom['Halal'] = warung.iloc[i[0]]['Halal'],
    ambil_rekom['Area_merokok'] = warung.iloc[i[0]]['Area_merokok'],
    ambil_rekom['Harga'] = warung.iloc[i[0]]['Harga'],
    ambil_rekom['Tempat_parkir'] = warung.iloc[i[0]]['Tempat_parkir'],
    ambil_rekom['Latitude'] = warung.iloc[i[0]]['Latitude'],
    ambil_rekom['Longitude'] = warung.iloc[i[0]]['Longitude']
    
    list_rekom.append(ambil_rekom)
   
    

In [179]:
list_rekom

[{'Nama_warung': ('Depot babi YOE',),
  'Halal': ('non halal',),
  'Area_merokok': ('ada',),
  'Harga': ('murah',),
  'Tempat_parkir': ('on street parking',),
  'Latitude': (-7.7734719,),
  'Longitude': 110.4110748},
 {'Nama_warung': ('Gemah Ripah - Special Masakan Daging Babi',),
  'Halal': ('non halal',),
  'Area_merokok': ('ada',),
  'Harga': ('murah',),
  'Tempat_parkir': ('on street parking',),
  'Latitude': (-7.7846564,),
  'Longitude': 110.3789477},
 {'Nama_warung': ('Nasi Goreng Babi Kranggan',),
  'Halal': ('non halal',),
  'Area_merokok': ('ada',),
  'Harga': ('murah',),
  'Tempat_parkir': ('on street parking',),
  'Latitude': (-7.7816487,),
  'Longitude': 110.3646812},
 {'Nama_warung': ('Warung Babi Si Lae',),
  'Halal': ('non halal',),
  'Area_merokok': ('ada',),
  'Harga': ('murah',),
  'Tempat_parkir': ('on street parking',),
  'Latitude': (-7.7854563,),
  'Longitude': 110.3787934},
 {'Nama_warung': ('bakso dan sate Babi pak Har',),
  'Halal': ('non halal',),
  'Area_mero

In [180]:
ambil_rekom

{'Nama_warung': ('bakso dan sate Babi pak Har',),
 'Halal': ('non halal',),
 'Area_merokok': ('ada',),
 'Harga': ('murah',),
 'Tempat_parkir': ('on street parking',),
 'Latitude': (-7.7727407,),
 'Longitude': 110.3264233}

In [188]:
warung_recom = []
for i in warung_similar:
    if i[1] >= 0.84:
        warung_recom.append(i)
    else:
        pass

In [189]:
warung_recom

[(233, 1.0),
 (242, 1.0),
 (244, 1.0),
 (245, 1.0),
 (246, 1.0),
 (0, 0.9230769230769231),
 (1, 0.9230769230769229),
 (232, 0.9230769230769229),
 (234, 0.9230769230769229),
 (237, 0.9230769230769229),
 (240, 0.9230769230769229),
 (241, 0.9230769230769229),
 (243, 0.9230769230769229),
 (247, 0.9230769230769229),
 (305, 0.9230769230769229),
 (341, 0.9230769230769229),
 (19, 0.846153846153846),
 (230, 0.846153846153846),
 (235, 0.846153846153846),
 (236, 0.846153846153846),
 (238, 0.846153846153846),
 (239, 0.846153846153846),
 (248, 0.846153846153846)]

In [201]:
display(warung[warung['Halal'] == 'non_halal'])

ID  Latitude   Longitude  \
0      1 -7.768875  110.317707   
1      2 -7.765697  110.344304   
19    20 -7.818566  110.364528   
230  233 -7.747771  110.362017   
232  235 -7.773496  110.411448   
233  236 -7.773472  110.411075   
234  237 -7.772725  110.391792   
235  238 -7.770619  110.397099   
236  239 -7.762582  110.397731   
237  240 -7.782023  110.362401   
238  241 -7.771420  110.446829   
239  242 -7.776676  110.341719   
240  243 -7.797432  110.365601   
241  244 -7.788131  110.301957   
242  245 -7.784656  110.378948   
243  246 -7.772316  110.342886   
244  247 -7.781649  110.364681   
245  248 -7.785456  110.378793   
246  249 -7.772741  110.326423   
247  250 -7.784470  110.363273   
248  251 -7.786317  110.302326   
305  308 -7.775652  110.415970   
341  344 -7.785103  110.352505   

                                           Nama_warung  \
0                                 Warung Bakso Babi 08   
1                           Rumah Makan 88 / panpan 88   
19                             Mediterranea Restaurant   
230                   Babi Q Resto Khusus Masakan Babi   
232         Bak & Mie - Spesial Babi Geprek & Mie Babi   
233                                     Depot babi YOE   
234                                              Pothz   
235                        Babi Panggang Racing Koh JW   
236                                        Lapo Laetta   
237                                      Kedai Piggies   
238                    Warung Makan Bu Kadek Khas Bali   
239                        Kong Kong Chinese & Seafood   
240                                 Sate Babi Ketandan   
241                  Rocky Daging Babi Segar dan Bakso   
242          Gemah Ripah - Special Masakan Daging Babi   
243  Warung 52 Babi Panggang & Spesial Menu Babi Fa...   
244                          Nasi Goreng Babi Kranggan   
245                                 Warung Babi Si Lae   
246                        bakso dan sate Babi pak Har   
247                                Sate Babi Maranatha   
248           DJOMED br. Tampubolon ( Rm daging babi )   
305                            Mc'B (Bukan Babi Biasa)   
341                                Rumah Makan Hao Mei   

                                                Alamat      Halal  \
0    Jl. Krandon, Area Sawah, Sidomoyo, Kec. Godean...  non_halal   
1    Jl. Kabupaten KM 1,5 No.98, Nusupan, Trihanggo...  non_halal   
19   Jl. Tirtodipuran No. 24 A Mantrijeron, Yogyaka...  non_halal   
230  Unnamed Road, 55284, Mlati Dukuh, Sendangadi, ...  non_halal   
232  Kompleks Pertokoan Babarsari No.37a, Kledokan,...  non_halal   
233  Unnamed Road, Kledokan, Caturtunggal, Kec. Dep...  non_halal   
234  Jl. STM Pembangunan No.14, Santren, Caturtungg...  non_halal   
235  Jl. Garuda Jl. Pringwulung No.162A, Pringwulun...  non_halal   
236  Selatan Hartono Mall, Jl. Kaliwaru No.mor 812,...  non_halal   
237      Cokrodiningratan, Kec. Jetis, Kota Yogyakarta  non_halal   
238  Kadirojo I, Purwomartani, Kec. Kalasan, Kabupa...  non_halal   
239  Jl. Kabupaten, Area Sawah, Nogotirto, Kec. Gam...  non_halal   
240  Jl. Ketandan Kulon, Ngupasan, Kec. Gondomanan,...  non_halal   
241  Gg. Padawa, Gancakan Wetan, Sidomulyo, Kec. Go...  non_halal   
242  Jl. Dr. Wahidin Sudirohusodo No.48, Kotabaru, ...  non_halal   
243  Ruko Abang Ireng Jalan Kabupaten no 52 km. 1, ...  non_halal   
244  Jl. Kranggan No.23, Cokrodiningratan, Kec. Jet...  non_halal   
245  Jl. Dr. Wahidin Sudirohusodo, Klitren, Kec. Go...  non_halal   
246  Cokro Gedok, Sidoarum, Kec. Godean, Kabupaten ...  non_halal   
247  Jl. Bumijo No.30c, Bumijo, Kec. Jetis, Kota Yo...  non_halal   
248  Jalan Pandawa RT.05/RW.18, Gancakan Wetan, Sid...  non_halal   
305  Ruko Babarsari BBC Plaza, Jalan Babarsari No.5...  non_halal   
341  Jl. HOS Cokroaminoto No.205, Tegalrejo, Kec. T...  non_halal   

    Area_merokok     Harga       Tempat_parkir  \
0            Ada     Murah  off_street_parking   
1            Ada     Mahal   on_street_

<h2> Simpan <i>random forest classifier model</i></h2>

In [190]:
import joblib
joblib.dump(rf_clf,'model_warung')

['model_warung']

In [249]:
def recommendation(prediksi):
    #recommended_warung = []
    warung_fav = rf_clf.predict([prediksi])[0]
    matrix_kriteria = model.fit_transform(warung['kriteria'])
    score = cosine_similarity(matrix_kriteria)
    
    index_fav = warung[warung['Nama_warung'] == warung_fav].index.values[0]
    # list all restuarants + cosine similarity score
    all_warung = list(enumerate(score[index_fav]))
    # show similar restaurant, sorted by score
    warung_similar = sorted(
    all_warung,
    key = lambda i: i[1],
    reverse = True
    )
    warung_recom = []
    for i in warung_similar:
        if i[1] > 0.84:
            warung_recom.append(i)
        else:
            pass

    # show 5 datas randomly
    list_rekom = []
    rekomendasi = random.choices(warung_recom, k = 5)
    
    for i in rekomendasi:
        
     print('Warung = {} | Halal = {} | Area Merokok = {} | Harga = {} | Tempat parkir = {}'.format(
        warung.iloc[i[0]]['Nama_warung'],
        warung.iloc[i[0]]['Halal'],
        warung.iloc[i[0]]['Area_merokok'],
        warung.iloc[i[0]]['Harga'],
        warung.iloc[i[0]]['Tempat_parkir'])
        )
    return #recommended_warung

In [250]:
Data = [0,1,1,0,0,0,1,0,1]
recommendation(data)

ValueError: could not convert string to float: 'Downloads/tempat_makan_2022-02-17.csv'

In [251]:
Data = [0,1,1,0,0,0,1,0,1]
#prediksi = rf_clf.predict([fitur])[0]
#warung_fav = prediksi
# print(data)
recommendation(data)

ValueError: could not convert string to float: 'Downloads/tempat_makan_2022-02-17.csv'

In [ ]:
class recommederSystem :
    def __init__(self, data,content_col)
        self.warung = pd.read_csv(data)
        self.c
    def fit(self):
    def recommend(self):